# Generated by Django 5.1.1 on 2024-09-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='image',
            field=models.ImageField(default='1', upload_to='apps/'),
            preserve_default=False,
        ),
    ]
