# Generated by Django 5.1.1 on 2024-09-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_app_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserApp',
        ),
    ]
