# Generated by Django 5.0.1 on 2024-09-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_userapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Success'), ('F', 'Failure')], default='P', max_length=1),
        ),
    ]
